### ISSUE TITLE
Tooltip may appear below the mouse pointer causing flickering

### ISSUE THREAD

**Issue by thg2k** [google/google-visualization-issues#2162]
Greetings,
I noticed in one of the diffchart samples that the tooltip might appear below the mouse arrow and cause a really bad flickering (extremely bad on FF 43.0.1 and moderately bad on Chrome 48), you should be able to see this on your own samples on this page:
https://google-developers.appspot.com/chart/interactive/docs/gallery/diffchart

EDIT: forgot to mention which example, I was referring to the diff pie chart, the one witih inner whiter values, if you hover on top of the inner values you will notice the problem

**Comment by lawtata** [comment]
Any news on this? I'm having the same problem on my application with pieCharts
Here's is ok -> https://developers.google.com/chart/
But here is failing -> https://google-developers.appspot.com/chart/interactive/docs/gallery/piechart

**Comment by chris-griffin** [comment]
I too have run into this issue. Any suggestions?

**Comment by chris-griffin** [comment]
I still have not been able to find the issue, but this bug is not present in v42 (the current version is 44). 

I simply altered this line from:

`google.charts.load('current', {'packages':['corechart']});`

to:

`google.charts.load('42', {'packages':['corechart']});`

It is now working as expected and not flickering.

**Comment by thg2k** [comment]
I can confirm this with Firefox 44.0.2 and Chrome 50.0.2661.75 and the current gcharts published on the link in the original report, here is a screenshot to better explain how to reproduce the problem:
![Screenshot of the problem](http://i.imgur.com/y6beINF.png)

If you move your mouse in that area of the chart you are able to move the pointer on top of the tooltip, and then the flickering happens.

**Comment by patawa91** [comment]
Any update on this issue? Is this going to be addressed in the next version? Does anyone have a good workaround other than loading version 42? This is a big pain point for us on this project.

**Comment by eghernqvist** [comment]
+1 on what @patawa91 said.

**Comment by murphyte** [comment]
I think this is what is happening:
1. mousing over the chart activates the popup
2. the popup is superimposed on top of the chart and under the pointer. This isn't always the case, but it's the situation that activates the flicker
3. the pointer is now no longer over the chart (because it's over the popup), and therefore the popup is removed.
4. Go to 1

If the logic for #3 is altered to either ignore the existence of the popup and detect the chart element underneath, or to include the popup itself as a chart element that activates the popup, then I think that would prevent the flicker.

**Comment by sruslanas** [comment]
Firefox 47. Same behavior here.

It is also failing on https://developers.google.com/chart/

**Comment by DmitryKmita** [comment]
Any estimates on solving this ticket as it totally breaks UX, especially for Pie charts.

**Comment by patawa91** [comment]
I'm really hoping this bug will get prioritized soon, and make it into the next release.

**Comment by neilkyle** [comment]
I'd also like this to be fixed. The pie chart is such a fundamental chart and this is not the best bug to have on it. Thanks

**Comment by SainathBommisetty** [comment]
Any update on this issue, I am also facing the same problem, I can't use version 42 as I am using Gantt Chart.

**Comment by kenseals** [comment]
A workaround I've found is to set pointer-events: none on the tooltip in your css:

`div.google-visualization-tooltip { pointer-events: none }`

**Comment by mhingston** [comment]
Thanks @kenseals, that works, but I had to modify the selector as follows:

`svg > g > g:last-child { pointer-events: none }`

**Comment by SainathBommisetty** [comment]
Thanks mhingston & kenseals, it solved the issue!!

**Comment by joallard** [comment]
Doesn't take a genius to know that you have to install the mouseover event on the tooltip as well for this not to happen.

**Comment by nealshan** [comment]
Thanks mhingston & kenseals, it solved the issue!!

**Comment by Nic062** [comment]
Thanks mhingston & kenseals, it solved the issue!!

**Comment by liqiang372** [comment]
just a heads up for @mhingston's solution.  This will literally disable any svg interaction including d3's force graph. If Google chart is your only concern, go for it. Otherwise, don't forget to test your other svg visualization.

**Comment by jakubkratina** [comment]
+1

**Comment by WireDoc** [comment]
That worked! This problem was plaguing my graphs and making them impractical to use, now they are working as intended.
THANKS AGAIN!

**Comment by exvayn** [comment]
i think this way is better
`svg > g:last-child > g:last-child { pointer-events: none }`
because my last legend on other graphs was disabled

**Comment by sudeesh** [comment]
pointer-events: none will not work on IE10. If anyone has faced this issue in IE10 please let me know the way to resolve it.

**Comment by DrNiels** [comment]
Has there been any process to this? I'm currently using google-chart via WebElement (https://www.webcomponents.org/element/GoogleWebComponents/google-chart).

Thus, it's contained within a shadow DOM and using the presented workaround does not really work without modifying the web component itself.

**Comment by estomagordo** [comment]
Also a bit surprised that this hasn't been solved.

**Comment by bencamilleri** [comment]
You can click the link below to a Bug/issue raised with Google. The more votes the more chance of it being resolved in the platform. 
[](https://issuetracker.google.com/u/2/issues/77888335)
https://issuetracker.google.com/u/2/issues/77888335

**Comment by brettwgreen** [comment]
You can also prevent the flicker by setting the following option:
`tooltip: { trigger: 'selection' }`

This avoids the problem by eliminating hover from the scene altogether by requiring clicks on the chart (or legend) to see the tooltip. I didn't like the idea of messing with the CSS to fix the flicker, and not a fan, in any case, of hover behavior due to limitations on touch screens.

Thought some of you may prefer this alternative solution.

**Comment by jcroa** [comment]
> i think this way is better
> `svg > g:last-child > g:last-child { pointer-events: none }`
> because my last legend on other graphs was disabled

tooltip can be showed into a 'g' container but also in a 'div' container. Then this way also works:

  .google-visualization-tooltip {  pointer-events:none; }

This rule could be included in the file:
https://www.gstatic.com/charts/46/css/core/tooltip.css

**Comment by bumbeishvili** [comment]
Any news on this annoying issue?

**Comment by Chris-KCIT** [comment]
This is still an issue. Disabling the tooltip on hover is a work around, but would really like to see it addressed.

**Comment by joshuapapa** [comment]
this does not work on angular. One solution is to call this function after every call of the draw function.

fixedTooltipFlickering(){
        var g = document.getElementsByTagName('g');
        var gLast = g[g.length-1];
        gLast.style.pointerEvents = "none";
}

**Comment by mathias22osterhagen22** [comment]
This issue is still existing in September 2021...😞

To make the fix work with `vuejs` and `vue-google-chart` you need to add a `style` not scoped like this: 
```html
<style >
svg > g:last-child > g.google-visualization-tooltip {
 pointer-events: none;
}
</style>
```

As it's not scoped, you can normally place it in any of your `.vue` files, personally I put it on the page where all my charts are because it just makes sens.

**Comment by vedantdhurve01** [comment]
This is Issue happened only crome

click other location on with the help of mouse but hover active upper 

but that exact code open in Mozilla thair properly work 
### 
![Screenshot (2)](https://user-images.githubusercontent.com/53587135/144181391-52c56bde-118e-42e3-99e2-8b8095a3185d.png)

**Comment by killmonger74** [comment]
Just modify your css file with this line `svg >g >g:last-child{pointer-events:none;}` and it will work fine.

**Comment by nidhiG2610** [comment]
> I still have not been able to find the issue, but this bug is not present in v42 (the current version is 44).
> 
> I simply altered this line from:
> 
> `google.charts.load('current', {'packages':['corechart']});`
> 
> to:
> 
> `google.charts.load('42', {'packages':['corechart']});`
> 
> It is now working as expected and not flickering.

This worked for me. Thanks!

**Comment by mariam-ali-k** [comment]
I was facing the same issue in one of my projects and tried this to fix the flickering problem. It is resolved for me.
```
svg g circle, svg g > path[stroke = "#636363"] {
      pointer-events: none !important;
  }

```

**Comment by jamesadrian27** [comment]
I also face the same issue on my vuejs 3 project and solve it using this solution 

`tooltip: { isHtml: true, ignoreBounds: true }`

**Comment by VinayakaD-RS** [comment]
> I was facing the same issue in one of my projects and tried this to fix the flickering problem. It is resolved for me.
> 
> ```
> svg g circle, svg g > path[stroke = "#636363"] {
>       pointer-events: none !important;
>   }
> ```

This might solve the flickering issue, but will make the legends for pie and donut chart non-clickable.
