### ISSUE TITLE
Gantt chart Uncaught TypeError: chart.draw is not a function

### ISSUE THREAD

**Issue by ngarcial** [google/google-visualization-issues#2177]
Please please please fix! The examples in the main page are also broken!

**Comment by ngarcial** [comment]
Issue was just fixed thank you!!!

**Comment by dlaliberte** [comment]
We changed nothing in the meantime.  

I just announced release of v44, and it appears that when we push out a new version, there are some hiccups in the system until the changes fully propagate.  If you get these kinds of errors, I suggest you refresh the page, flushing your cache if necessary.  If a problem persists, please give us enough details, such as a working example, so that we can determine the cause of the problem.  Thanks.

**Comment by ngarcial** [comment]
Thanks! I was just showing a prototype to a partner and it was working one minute and the next it wasn't. Will try flushing my cache next time. Thanks for the amazing work :)
