### ISSUE TITLE
loader.js:149 Uncaught TypeError: d is not a function(…)

### ISSUE THREAD

**Issue by thopah** [google/google-visualization-issues#2403]
this error happens on 11/22/2016 at 5pm. Please fixed this asap. Thank you .

Error: 
loader.js:149 Uncaught TypeError: d is not a function(…)

**Comment by dlaliberte** [comment]
Yes, sorry about that.  My bad!  I broke all charts using the new loader with version 45 (or current).  I updated for the new loader for the new version, but forgot a backward compatibility check.    I repaired it quickly, but the old version has a cache lifetime of 1 hour.

So this should be fixed within an hour.  I shortened the lifetime to 1 minute.  If you can switch to using '44' instead of 'current' or '45' (or 'upcoming') that should fix it for you now.

**Comment by whitephoenix117** [comment]
I was able to "fix" the issue by rolling back to stable version 44

**Comment by whitephoenix117** [comment]
I tried version 45 just now & it was still reproducing the error. Hopefully will be resolved when the cache clears.
