### ISSUE TITLE
GeoChart - USA States doesn't work (e.g. US-PA)

### ISSUE THREAD

**Issue by vladiiic** [google/google-visualization-issues#2821]
``` jsapi_compiled_default_module.js:72 Uncaught SyntaxError: Unexpected token c in JSON at position 0
    at JSON.parse (<anonymous>)
    at jsapi_compiled_ui_module.js:1210
    at e.JJ (jsapi_compiled_default_module.js:79)
    at gvjs_gj (jsapi_compiled_default_module.js:82)
    at gvjs_dj (jsapi_compiled_default_module.js:82)
    at gvjs_4i.Gna (jsapi_compiled_default_module.js:81)
    at gvjs_2i (jsapi_compiled_default_module.js:76) ``` 

 function gvjs_SM(a,b,c,d){gvjs_ML(gvjs_QM+"/"+a+"/"+(b+".js")).then(function(e){var f=b.replace("-","$");e=e.replace(new RegExp("^[\\s\\S]*google_visualization_geochart_"+(f+"\\s*=\\s*"),"g"),"");e=e.replace(/;[\s]*$/g,"");e=JSON.parse(e);c&&c(e);return e},function(e){d&&d(e)})}

**Comment by dlaliberte** [comment]
Hi @vladiiic.  Could you provide more details about how you are loading Google Charts, and include a sample of your data and options, enough to reproduce the problem.   Thanks.

**Comment by vladiiic** [comment]
> Hi @vladiiic. Could you provide more details about how you are loading Google Charts, and include a sample of your data and options, enough to reproduce the problem. Thanks.

Hi, I wrote example on codepen :
https://codepen.io/vladiiic/pen/vYNzxXx

Or you need real data example?

**Comment by dlaliberte** [comment]
Thanks.  I see the error, and the cause.  I should be able to fix it shortly.

**Comment by vladiiic** [comment]
Nice, glad to be of help  :)

**Comment by cpenn81** [comment]
Hi @dlaliberte. I've had multiple charts stop working today for seemingly no reason and after a bit of troubleshooting I was finally able to find this Github issue, glad to see it wasn't just me. FYI, US-MO is also not working, I'm getting the same error as @vladiiic showed in the codepen. Thanks!

**Comment by dlaliberte** [comment]
This should be fixed now.  I pushed out a new release with the fix, 48.1.   Loading '48' will automatically redirect to '48.1'.

**Comment by cpenn81** [comment]
Thanks for fixing that issue @dlaliberte . The map I used that showed the state of Missouri is now working, however my map that shows counties in Missouri (region codes such as MO-01, MO-02, etc) is still not working and is giving me the same error "Unexpected token / in JSON at position 15" at jsapi_compiled_default_module.js:72. Should I open a new issue? Thanks!

**Comment by cpenn81** [comment]
Thanks for fixing that issue @dlaliberte . The map we have showing the state of Missouri is now working, however we have a map with custom regions that is throwing the same error. "Unexpected token / in JSON at position 15" at jsapi_compiled_default_module.js:72. Should I open a new issue?Thanks!

Fiddle:

https://jsfiddle.net/MoAudit/cLdr0543/

**Comment by dlaliberte** [comment]
Hi Coty.  As I mentioned in the announcement about v48, the setMapsSource method that had been available up until version 45 has been restored, but with 2 conditions. The file needs to use strict JSON formatting for the data portion of it, with no intervening comments, and the server must allow access from other domains (i.e. cross-origin access).   Sounds like you are only having an issue with the JSON formatting, and the unexpected token is the start of a comment.

You can switch your example to load '45' and it works using the old method, but it would be better if you can switch to the new version.

**Comment by cpenn81** [comment]
Everything is working now, thanks a ton!
